### ISSUE TITLE
(feat): Allow generating data types that aren't bound to static lifetimes

### ISSUE THREAD

**Issue by vi013t** [cptpiepmatz/static-toml#3]
It'd be really handy to have a configuration option in `#[static_toml(...)]` that tells the macro to generate structs with owned types instead of lifetime-bounded types.

For example, say I'm making an application that the user can configure with a TOML file. I might want to do something like "use the TOML provided by the user if it exists, otherwise, use the default TOML config that's embedded at compile-time". That would look something like this:

```rust
static_toml::static_toml! {
    #[derive(serde::Deserialize)]
    static DEFAULT_CONFIG = include_toml!("default_config.toml");
}

fn main() {
    let user_config_toml = std::fs::read_to_string("user_config.toml");
    let user_config = user_config_toml.map_or(DEFAULT_CONFIG, |config| toml_edit::de::from_str(&config).unwrap());
}
```

...but this isn't possible. The types create by `static_toml` use things like `&'static str`, which means `serde` can't deserialize into it, because that data exists at runtime and won't necessarily have a static lifetime. Thus, the `#[derive(serde::Deserialize)]` causes a compile-time error.

I'd be really convenient if we could do something like this:

```rust
static_toml::static_toml! {
    #[derive(serde::Deserialize)]
    #[static_toml(owned = true)]
    static DEFAULT_CONFIG = include_toml!("default_config.toml");
}
```

...that'd generate owned types, such as using `String`  over `&'static str` and `Vec<T>` over `&'static [T]`, etc.

**Comment by cptpiepmatz** [comment]
@vi013t I’ve been thinking about your issue and I think using [`Cow`](https://doc.rust-lang.org/stable/std/borrow/enum.Cow.html) is the way to go. It lets me handle both borrowed and owned values in the same place. If I replaced `&'static str` with `String`, we'd lose the static values, which is kind of the whole point of this crate. With `Cow`, I can still use static slices, but these fields can also hold owned values at runtime, so it solves your problem. Do me a favor and experiment with the feature in #4. Maybe I missed something.

```toml
[dependencies.static-toml]
git = "https://github.com/cptpiepmatz/static-toml.git"
branch = "cows" # 🐄
```

**Comment by vi013t** [comment]
I think `Cow` is a fantastic option for this; I'm surprised I didn't think of it given that that's basically `Cow`'s entire purpose.

Your branch seems to work as expected from my testing, awesome work! Deriving `serde::Deserialize`, for example, doesn't cause any errors now. Thanks a lot! 

However, the more I consider this use case, the more I wonder if it's out of the scope of `static_toml`. If you allow the data to be instantiated at runtime, it brings up a lot of questions&mdash; Can we make optional properties? Can we have a section that allows arbitrary keys (like `HashMap<String, SomeValueType>`)? How would these things even be expressed in the macro? In my opinion these kinds of features are out of scope for this crate, which is just meant to allow embedding TOML documents as strongly-typed static values.

Those use cases, I imagine, are best handled by defining your types manually and deriving `serde::Deserialize` on them, and then just building the default value at runtime. This crate, on the other hand, would just be for what it was made for&mdash; statically embedding TOML files at compile-time.

Ultimately it's your choice. I think the work you've done on this branch is great and useful; I just worry that it's pushing the crate out of the scope of it's original purpose of just static embedding. What do you think? Is allowing runtime-instantiation a direct opposition against that original purpose?

Either way, thanks for all your work! That was incredibly fast and works like a charm.

**Comment by cptpiepmatz** [comment]
I had situations where exactly this change would help me too, so I will keep it. But you're right, anything that goes against statically embedding data is out of scope here, especially optional data.
